# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b26ba197d7d1b2e6b39a26ecce1b9831d5ac57e0ae2e9a34b770766d4780777e0b84c53c1ac2d2f9c6a4e7d40bc69953588e2d2685a3043ce0c168c599d7f1

test:
  secret_key_base: fd1abc2f1dc504730a0c9b0b2898b45777125cc94eff7884f72b1f66de37f27e086e9af5176285a5ba06a687587577f725be67ffe3ee113b3051e7fab55820c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
